export interface DemoPnm {
  id: string;
  name: string;
  year: string;
  major: string;
  gpa: number;
  hometown: string;
  photo: string;
  tags: string[];
  noteCount: number;
  voteSummary: { up: number; down: number; star: number };
  latestNote?: { author: string; text: string };
}

export const DEMO_PNMS: DemoPnm[] = [
  {
    id: "demo-1",
    name: "Marcus Chen",
    year: "Freshman",
    major: "Computer Science",
    gpa: 3.91,
    hometown: "Palo Alto, CA",
    photo: "https://i.pravatar.cc/600?img=1",
    tags: ["legacy", "athlete"],
    noteCount: 4,
    voteSummary: { up: 12, down: 1, star: 3 },
    latestNote: { author: "JS", text: "Great convo at the smoker — knows three brothers already." },
  },
  {
    id: "demo-2",
    name: "Diego Alvarez",
    year: "Sophomore",
    major: "Mechanical Engineering",
    gpa: 3.74,
    hometown: "Austin, TX",
    photo: "https://i.pravatar.cc/600?img=2",
    tags: ["transfer"],
    noteCount: 2,
    voteSummary: { up: 9, down: 2, star: 1 },
    latestNote: { author: "RP", text: "Quiet but very sharp; played D1 lacrosse." },
  },
  {
    id: "demo-3",
    name: "Jordan Patel",
    year: "Freshman",
    major: "Economics",
    gpa: 3.88,
    hometown: "Chicago, IL",
    photo: "https://i.pravatar.cc/600?img=3",
    tags: ["legacy", "scholar"],
    noteCount: 5,
    voteSummary: { up: 15, down: 0, star: 4 },
    latestNote: { author: "TM", text: "Top of his pledge class material. Easy yes." },
  },
  {
    id: "demo-4",
    name: "Wesley Kim",
    year: "Freshman",
    major: "Pre-Med",
    gpa: 3.95,
    hometown: "Seattle, WA",
    photo: "https://i.pravatar.cc/600?img=4",
    tags: ["scholar"],
    noteCount: 3,
    voteSummary: { up: 7, down: 3, star: 1 },
  },
  {
    id: "demo-5",
    name: "Ethan Brooks",
    year: "Sophomore",
    major: "Business",
    gpa: 3.42,
    hometown: "Charlotte, NC",
    photo: "https://i.pravatar.cc/600?img=5",
    tags: ["athlete"],
    noteCount: 1,
    voteSummary: { up: 5, down: 4, star: 0 },
  },
  {
    id: "demo-6",
    name: "Noah Williams",
    year: "Freshman",
    major: "Finance",
    gpa: 3.81,
    hometown: "Boston, MA",
    photo: "https://i.pravatar.cc/600?img=6",
    tags: ["legacy"],
    noteCount: 6,
    voteSummary: { up: 11, down: 1, star: 2 },
    latestNote: { author: "AS", text: "Dad is an alum. Brought it up unprompted, in a good way." },
  },
  {
    id: "demo-7",
    name: "Liam O'Connor",
    year: "Freshman",
    major: "Political Science",
    gpa: 3.63,
    hometown: "Denver, CO",
    photo: "https://i.pravatar.cc/600?img=7",
    tags: [],
    noteCount: 2,
    voteSummary: { up: 6, down: 2, star: 0 },
  },
  {
    id: "demo-8",
    name: "Andre Jackson",
    year: "Sophomore",
    major: "Biology",
    gpa: 3.78,
    hometown: "Atlanta, GA",
    photo: "https://i.pravatar.cc/600?img=8",
    tags: ["athlete", "scholar"],
    noteCount: 3,
    voteSummary: { up: 10, down: 1, star: 2 },
  },
  {
    id: "demo-9",
    name: "Tyler Nguyen",
    year: "Freshman",
    major: "Mathematics",
    gpa: 3.99,
    hometown: "San Diego, CA",
    photo: "https://i.pravatar.cc/600?img=9",
    tags: ["scholar"],
    noteCount: 4,
    voteSummary: { up: 13, down: 0, star: 3 },
  },
  {
    id: "demo-10",
    name: "Hunter Davis",
    year: "Junior",
    major: "Marketing",
    gpa: 3.51,
    hometown: "Nashville, TN",
    photo: "https://i.pravatar.cc/600?img=10",
    tags: [],
    noteCount: 1,
    voteSummary: { up: 4, down: 5, star: 0 },
  },
  {
    id: "demo-11",
    name: "Riley Thompson",
    year: "Freshman",
    major: "Environmental Studies",
    gpa: 3.72,
    hometown: "Portland, OR",
    photo: "https://i.pravatar.cc/600?img=11",
    tags: ["athlete"],
    noteCount: 2,
    voteSummary: { up: 8, down: 2, star: 1 },
  },
  {
    id: "demo-12",
    name: "Sam Rivera",
    year: "Sophomore",
    major: "Architecture",
    gpa: 3.66,
    hometown: "Miami, FL",
    photo: "https://i.pravatar.cc/600?img=12",
    tags: ["transfer", "scholar"],
    noteCount: 3,
    voteSummary: { up: 9, down: 1, star: 1 },
  },
];
