-- 0005_update_votes_schema.sql
--
-- INTENTIONALLY A NO-OP. Do not add statements here.
--
-- History: this migration originally tried to convert the legacy votes shape
-- (voter_id / score / is_favorite) to the current one (voter_user_id / value /
-- favorite). It never ran anywhere, in any environment, because it opened a
-- nested `DO $$ ... $$` block inside an outer `DO $$ ... $$` block. Postgres
-- terminates the outer dollar-quoted string at the inner `$$`, so the file
-- failed with `ERROR: syntax error at or near "BEGIN"` on every attempt.
--
-- It also carried a data-corrupting mapping: it treated `score = 1` as YES and
-- `score = 0` as NO, but `votes.score` is `CHECK (score >= 1 AND score <= 10)`,
-- where 1 is the *lowest* rating. Had it run, every downvote would have been
-- recorded as a YES and every other vote as UNKNOWN. The correct mapping is the
-- one the API itself uses (see python_server/routes.py): >= 7 -> YES,
-- <= 4 -> NO, otherwise UNKNOWN.
--
-- Because it never applied, editing it is safe. It is emptied rather than
-- repaired so that votes reconciliation lives in exactly one place:
-- 0013_reconcile_schema.sql. Two migrations independently reconciling the same
-- table is what produced the schema drift this cleanup exists to fix.
--
-- See docs/AUDIT-2026-08.md and 0013_reconcile_schema.sql.

SELECT 1;
